Match/Filter ip/cidr, deprecated existing ip flag and conversion with cidr/stdin
projectdiscovery/mapcidr pull request #87
Opened 2022-06-21 19:04 UTC by LuitelSamikshya

2022-06-22 07:02 UTC, Mzack9999 commented
@ehsandeep the behavior described in https://github.com/projectdiscovery/mapcidr/issues/79 should be supported (CIDR expansion from stdin + IPs conversion)?

```console
echo 192.168.1.224/30 | mapcidr -t6 -silent

00:00:00:00:00:ffff:c0a8:01e0
00:00:00:00:00:ffff:c0a8:01e1
00:00:00:00:00:ffff:c0a8:01e2
00:00:00:00:00:ffff:c0a8:01e3
```

2022-06-23 10:27 UTC, ehsandeep commented
> the behavior described in #79 should be supported (CIDR expansion from stdin + IPs conversion)?

@Mzack9999 CIDR expansion is the default behavior of mapcidr, and  IPs conversion as `-t6` is specified, so yes, this is expected behavior.

2022-06-23 10:43 UTC, ehsandeep requested changes
..

2022-07-01 17:27 UTC, ehsandeep approved these changes

2022-07-10 14:24 UTC, Mzack9999 approved these changes

2022-07-10 19:25 UTC, merged