Add IP range input support (ipv4, ipv6)
projectdiscovery/mapcidr pull request #99
Opened 2022-09-05 08:24 UTC by ShubhamRasal

This PR implements IP range input support (ipv4, ipv6)  described in #98 

- `rangeTOCIDR()` does not checks the IP range correctness so create `GetCIDRFromIPRange()`.
- Add `GetCIDRFromIPRange()` function in `ip.go` which accepts the first and last IP and returns the sorted list of CIDR.
- `GetCIDRFromIPRange()` returns error if range is not valid. It uses the `rangeTOCIDR()` function to get the CIDR list.
- Add test cases for
    - ipv4 range which returns a single CIDR
    - ipv4 range which returns multiple CIDRs
    - ipv6 range which returns multiple CIDRs
    - Wrong IP range, which returns an error
- Update README.md to add the IP range input support documentation.

2022-09-05 10:02 UTC, ehsandeep requested changes
Thank you @ShubhamRasal for the PR.

Range input support can be generic and not specific to `-aggregate` feature.

2022-09-06 18:03 UTC, ehsandeep approved these changes
```console
$ echo 10.40.0.0-10.40.0.2 | ./mapcidr -a -silent
10.40.0.0/31
10.40.0.2/32

$ echo 10.40.0.0-10.40.0.2 | ./mapcidr -silent
10.40.0.0
10.40.0.1
10.40.0.2
```

2022-09-09 05:28 UTC, Mzack9999 requested changes
suggesting some minor changes

2022-09-09 05:28 UTC, Mzack9999 commented on cmd/mapcidr/main.go
> +	IPRangeInput          bool
I think this bool can be removed

2022-09-09 05:28 UTC, Mzack9999 commented on cmd/mapcidr/main.go
> +			if len(ipRange)%2 == 1 {
I think this can be simplified to:
```go
len(ipRange)>2
```

2022-09-09 05:28 UTC, Mzack9999 commented on cmd/mapcidr/main.go
> +	if options.IPRangeInput {
`options.IPRangeInput` is not needed. We can directly iterate on `ipRangeList` (it will be skipped if empty)

2022-09-09 05:28 UTC, Mzack9999 commented on cmd/mapcidr/main.go
> +
please remove this new line

2022-09-09 05:28 UTC, Mzack9999 commented on ip_test.go
> +				if !strings.Contains(err.Error(), tt.expectedError) {
```go
require.Contains(t, err.Error(), tt.expectedError)
```

2022-09-09 05:28 UTC, Mzack9999 commented on ip_test.go
> +				if !reflect.DeepEqual(cidrStringList, tt.want) {
```go
require.Equal(t, tt.want, cidrStringList)
```

2022-09-09 05:28 UTC, Mzack9999 commented on cmd/mapcidr/main_test.go
> +			if !reflect.DeepEqual(outputlist, tt.expectedOutput) {
```go
require.Equal(t, tt.expectedOutput, outputlist)
```

2022-09-11 19:11 UTC, Ice3man543 approved these changes

2022-09-12 05:40 UTC, merged